<div class="row-fluid" id="articles-container">
  <div class="span12">
      <?php 
      if (!empty($formOkMessages)) {
        foreach ($formOkMessages as $message) { ?>
      <div class="alert alert-success">
        <button data-dismiss="alert" class="close" type="button">×</button>
        <?php echo $this->escapeHtml($message) ?>
      </div>
      <?php
        }
      }?>
      <?php
      if (!empty($formErrorMessages)) {
        foreach ($formErrorMessages as $message) { ?>
      <div class="alert alert-error">
        <button data-dismiss="alert" class="close" type="button">×</button>
        <?php echo $this->escapeHtml($message) ?>
      </div>
      <?php
        }
      }?>
      <div class="pull-right text-info"><?php echo $this->translate(sprintf('Revision: #%d', $article ? $article->getRevision() : 0)) ?></div>
<?php
    $form->prepare();
    $form->setAttribute('action', $this->url('admin/libra-article/article', array(
        'id' => $id,
    ), array(
        'query' => array(
            'uid' => $uid,
            'locale' => null
        )
    )));
    echo $this->form()->openTag($form);
    echo $this->formInput($form->get('id'));
    echo $this->formElementErrors($form->get('id'));
    if (LibraModuleManager\Module::isModulePresent('LibraLocale')) {
        echo $this->formLabel($form->get('locale'));
        echo $this->formSelect($form->get('locale'));
        echo $this->formElementErrors($form->get('locale'));
    }
    echo $this->formLabel($form->get('heading'));
    echo $this->formInput($form->get('heading'));
    echo $this->formElementErrors($form->get('heading'));
    echo $this->formLabel($form->get('alias'));
    echo $this->formInput($form->get('alias'));
    echo $this->formElementErrors($form->get('alias'));
    echo $this->formLabel($form->get('headTitle'));
    echo $this->formInput($form->get('headTitle'));
    echo $this->formElementErrors($form->get('headTitle'));
    echo '<div id="metaKeywordsLength" class="pull-right"></div>';
    echo $this->formLabel($form->get('metaKeywords'));
    echo $this->formInput($form->get('metaKeywords'));
    echo $this->formElementErrors($form->get('metaKeywords'));
    echo '<div id="metaDescriptionLength" class="pull-right"></div>';
    echo $this->formLabel($form->get('metaDescription'));
    echo $this->formInput($form->get('metaDescription'));
    echo $this->formElementErrors($form->get('metaDescription'));
    $googlePreview = $this->googlePreview ?: $this->translate('Preview will be available after save article');
    echo <<<GP
    <div id="googlePreview">
        <span>Preview:</span>
        <div>$googlePreview</div>
    </div>
GP;
    echo $this->formLabel($form->get('content'));
    echo $this->formCkeditor($form->get('content'));
    echo $this->formElementErrors($form->get('content'));
    echo '<br />';
    echo $this->formElement($form->get('csrf'));
    echo $this->formElementErrors($form->get('csrf'));
    echo $this->formSubmit($form->get('submit'));
?>
<?php echo $this->form()->closeTag() ?>
  </div><!--/span-->
</div><!--/row-->
<style>
    #googlePreview {
        height: 100px;
        margin: 2px 0 10px;
    }

    #googlePreview > div {
        margin: 2px 0 10px 20px;
        width: 512px;
        border: solid 0px gray;
    }
</style>
<script>
jQuery(function($) {
    $("#articleForm input[name=metaKeywords]").keyup(function() {
        $("#metaKeywordsLength").text($(this).val().length);
    }).keyup();
    $("#articleForm input[name=metaDescription]").keyup(function() {
        $("#metaDescriptionLength").text($(this).val().length);
    }).keyup();
});
</script>