<div class="row-fluid" id="articles-container">
  <div class="span12">
      <div class="pull-right text-info"><?php echo $this->translate(sprintf('Revision: #%d', $article->getRev())) ?></div>
<?php
    $form->prepare();
    $form->setAttribute('action', $this->url('admin/libra-article/article', array('id' => $id)));
    echo $this->form()->openTag($form);
    echo $this->formInput($form->get('id'));
    echo $this->formElementErrors($form->get('id'));
    echo $this->formLabel($form->get('heading'));
    echo $this->formInput($form->get('heading'));
    echo $this->formElementErrors($form->get('heading'));
    echo $this->formLabel($form->get('alias'));
    echo $this->formInput($form->get('alias'));
    echo $this->formElementErrors($form->get('alias'));
    echo $this->formLabel($form->get('headTitle'));
    echo $this->formInput($form->get('headTitle'));
    echo $this->formElementErrors($form->get('headTitle'));
    echo $this->formLabel($form->get('metaKeywords'));
    echo $this->formInput($form->get('metaKeywords'));
    echo $this->formElementErrors($form->get('metaKeywords'));
    echo $this->formLabel($form->get('metaDescription'));
    echo $this->formInput($form->get('metaDescription'));
    echo $this->formElementErrors($form->get('metaDescription'));
    echo $this->formLabel($form->get('content'));
    echo $this->formCkeditor($form->get('content'));
    echo $this->formElementErrors($form->get('content'));
    echo '<br />';
    echo $this->formElement($form->get('csrf'));
    echo $this->formElementErrors($form->get('csrf'));
    echo $this->formSubmit($form->get('submit'));
?>
<?php echo $this->form()->closeTag() ?>
  </div><!--/span-->
</div><!--/row-->
