<?php
$articles = (array)$this->vars();
unset ($articles['partialCounter']);
$col = new stdClass;
$col->headline = '';
$col->alias = '';
$col->published = '';
$col->created = '';
$col->ordering = '';
$col->id = '';
?>
<tr>
  <td style="vertical-align: middle"><?php echo $this->partialCounter ?></td>
  <?php foreach ($articles as $article) {
    $col->headline      .= $this->partial('libra-article/admin-articles/articles-td-headline', $article);
    $col->alias         .= $this->partial('libra-article/admin-articles/articles-td-alias', $article);
    $col->published     .= $this->partial('libra-article/admin-articles/articles-td-published', $article);
    $col->created       .= $this->partial('libra-article/admin-articles/articles-td-created', $article);
    $col->ordering      .= $this->partial('libra-article/admin-articles/articles-td-ordering', $article);
    $col->id            .= $this->partial('libra-article/admin-articles/articles-td-id', $article);
  }
  $url = $this->url('admin/libra-article/article', array(), array(
      'query' => array(
          'uid' => $article->getUid(),
          'locale' => null
      )
  ));
  ?>
  <td>
    <ul class="list-unstyled">
      <li style="float: right;">
        <a href="<?php echo $url ?>" class="icon-plus" title="Add article to this group"></a>
      </li>
      <?php echo $col->headline ?>
    </ul>
  </td>
  <td><ul class="list-unstyled"><?php echo $col->alias ?></ul></td>
  <td><ul class="list-unstyled"><?php echo $col->published ?></ul></td>
  <td><ul class="list-unstyled"><?php echo $col->created ?></ul></td>
  <td><ul class="list-unstyled"><?php echo $col->ordering ?></ul></td>
  <td><ul class="list-unstyled"><?php echo $col->id ?></ul></td>
</tr>

