<?php
$data = array(
    'heading'   => 'Libra Article Admin',
    'formId'    => 'articles',
    'buttons'   => (object) array(
        'addnew' => (object) array(
            'formAction' => $this->url('admin/libra-article/article', array('action' => 'edit')),
            'method' => 'GET',
        ),
        'publish' => (object) array(
            'formAction' => $this->url('admin/libra-article/articles', array('action' => 'publish')),
        ),
        'unpublish' => (object) array(
            'formAction' => $this->url('admin/libra-article/articles', array('action' => 'unpublish')),
        ),
        'delete' => (object) array(
            'formAction' => $this->url('admin/libra-article/articles', array('action' => 'remove')),
        ),
    ),
);
extract($data);
?>
<div class="row-fluid" id="toolbar">
  <div class="col-sm-12">
  <div class="well">
    <div class="btn-toolbar pull-right" role="toolbar" style="margin-top: 8px;">
      <div class="btn-group">
          <button class="btn btn-default" title="Add New"
            form="<?php echo $formId ?>"
            formmethod="<?php echo $buttons->addnew->method ?: 'GET' ?>"
            formaction="<?php echo $buttons->addnew->formAction ?>"
          >
            <span class="glyphicon glyphicon-plus"></span>
          </button>
          <button class="btn btn-default" title="Publish"
            form="<?php echo $formId ?>"
            formaction="<?php echo $buttons->publish->formAction ?>"
          >
            <span class="glyphicon glyphicon-ok"></span>
          </button>
          <button class="btn btn-default"  title="Unpublish"
            form="<?php echo $formId ?>"
            formaction="<?php echo $buttons->unpublish->formAction ?>"
          >
            <span class="glyphicon glyphicon-off"></span>
          </button>
      </div>
      <div class="btn-group">
          <button class="btn btn-default" title="Delete" form="<?php echo $formId ?>"
            formaction="<?php echo $buttons->delete->formAction ?>"
            onclick="return confirm('You couldn\'t revert it. Are you shure?')"
          >
            <span class="glyphicon glyphicon-remove"></span>
          </button>
      </div>
    </div>
    <h1><?php echo $heading ?></h1>
  </div>
  </div><!--/span-->
</div><!--/row-->
