<section id="toolbar">
    <?php echo $this->render('libra-article/admin-articles/toolbar') ?>
</section>
<section>
    <form id="articles" method="post">
    <table class="table table-bordered table-striped table-condensed">
        <thead>
            <tr>
                <th width="1%"><?php echo $this->translate('#') ?></th>
                <th><?php echo $this->translate('Headline') ?></th>
                <th><?php echo $this->translate('Alias') ?></th>
                <th><?php echo $this->translate('Published') ?></th>
                <th><?php echo $this->translate('Created') ?></th>
                <th><?php echo $this->translate('Order') ?></th>
                <th width="1%"><?php echo $this->translate('Id') ?></th>
            </tr>
        </thead>
        <!--tfoot>
            <tr><td class="centered" colspan="100">paging</td></tr>
        </tfoot-->
        <tbody>
            <?php echo $this->partialLoop('libra-article/admin-articles/articles-tr', array($articles)) ?>
        </tbody>
    </table>
    </form>
</section>
