<section>
    <?php $data = array(
        'heading'   => 'Libra Article Admin',
        'formId'    => 'articles',
        'buttons'   => (object) array(
            'addnew' => (object) array(
                'formAction' => $this->url('admin/libra-article/index', array('controller' => 'admin-index', 'action' => 'edit')),
                'method' => 'GET',
            ),
            'publish' => (object) array(
                'formAction' => $this->url('admin/libra-article/index', array('controller' => 'admin-index', 'action' => 'publish')),
            ),
            'unpublish' => (object) array(
                'formAction' => $this->url('admin/libra-article/index', array('controller' => 'admin-index', 'action' => 'unpublish')),
            ),
            'delete' => (object) array(
                'formAction' => $this->url('admin/libra-article/index', array('controller' => 'admin-index', 'action' => 'delete')),
            ),
        ),
    ); ?>
    <?php echo $this->render('libra-article/admin-index/toolbar', $data) ?>
</section>
<section>
    <form id="articles" method="post">
    <table class="table table-bordered table-striped table-condensed">
        <thead>
            <tr>
                <th width="1%"><?php echo $this->translate('#') ?></th>
                <th><?php echo $this->translate('Headline') ?></th>
                <th><?php echo $this->translate('Alias') ?></th>
                <th><?php echo $this->translate('Published') ?></th>
                <th><?php echo $this->translate('Created') ?></th>
                <th><?php echo $this->translate('Order') ?></th>
                <th width="1%"><?php echo $this->translate('Id') ?></th>
            </tr>
        </thead>
        <!--tfoot>
            <tr><td class="centered" colspan="100">paging</td></tr>
        </tfoot-->
        <tbody>
            <?php echo $this->partialLoop('libra-article/admin-index/articles-tr', array($articles)) ?>
        </tbody>
    </table>
    </form>
</section>
